export let countryData =
{
    "Afghanistan": "https://www.countryflags.io/AF/shiny/64.png",
    "Åland Islands": "https://www.countryflags.io/AX/shiny/64.png",
    "Albania": "https://www.countryflags.io/AL/shiny/64.png",
    "Algeria": "https://www.countryflags.io/DZ/shiny/64.png",
    "American Samoa": "https://www.countryflags.io/AS/shiny/64.png",
    "AndorrA": "https://www.countryflags.io/AD/shiny/64.png",
    "Angola": "https://www.countryflags.io/AO/shiny/64.png",
    "Anguilla": "https://www.countryflags.io/AI/shiny/64.png",
    "Antarctica": "https://www.countryflags.io/AQ/shiny/64.png",
    "Antigua and Barbuda": "https://www.countryflags.io/AG/shiny/64.png",
    "Argentina": "https://www.countryflags.io/AR/shiny/64.png",
    "Armenia": "https://www.countryflags.io/AM/shiny/64.png",
    "Aruba": "https://www.countryflags.io/AW/shiny/64.png",
    "Australia": "https://www.countryflags.io/AU/shiny/64.png",
    "Austria": "https://www.countryflags.io/AT/shiny/64.png",
    "Azerbaijan": "https://www.countryflags.io/AZ/shiny/64.png",
    "Bahamas": "https://www.countryflags.io/BS/shiny/64.png",
    "Bahrain": "https://www.countryflags.io/BH/shiny/64.png",
    "Bangladesh": "https://www.countryflags.io/BD/shiny/64.png",
    "Barbados": "https://www.countryflags.io/BB/shiny/64.png",
    "Belarus": "https://www.countryflags.io/BY/shiny/64.png",
    "Belgium": "https://www.countryflags.io/BE/shiny/64.png",
    "Belize": "https://www.countryflags.io/BZ/shiny/64.png",
    "Benin": "https://www.countryflags.io/BJ/shiny/64.png",
    "Bermuda": "https://www.countryflags.io/BM/shiny/64.png",
    "Bhutan": "https://www.countryflags.io/BT/shiny/64.png",
    "Bolivia": "https://www.countryflags.io/BO/shiny/64.png",
    "Bosnia and Herzegovina": "https://www.countryflags.io/BA/shiny/64.png",
    "Botswana": "https://www.countryflags.io/BW/shiny/64.png",
    "Bouvet Island": "https://www.countryflags.io/BV/shiny/64.png",
    "Brazil": "https://www.countryflags.io/BR/shiny/64.png",
    "British Indian Ocean Territory": "https://www.countryflags.io/IO/shiny/64.png",
    "Brunei Darussalam": "https://www.countryflags.io/BN/shiny/64.png",
    "Bulgaria": "https://www.countryflags.io/BG/shiny/64.png",
    "Burkina Faso": "https://www.countryflags.io/BF/shiny/64.png",
    "Burundi": "https://www.countryflags.io/BI/shiny/64.png",
    "Cambodia": "https://www.countryflags.io/KH/shiny/64.png",
    "Cameroon": "https://www.countryflags.io/CM/shiny/64.png",
    "Canada": "https://www.countryflags.io/CA/shiny/64.png",
    "Cape Verde": "https://www.countryflags.io/CV/shiny/64.png",
    "Cayman Islands": "https://www.countryflags.io/KY/shiny/64.png",
    "Central African Republic": "https://www.countryflags.io/CF/shiny/64.png",
    "Chad": "https://www.countryflags.io/TD/shiny/64.png",
    "Chile": "https://www.countryflags.io/CL/shiny/64.png",
    "China": "https://www.countryflags.io/CN/shiny/64.png",
    "Christmas Island": "https://www.countryflags.io/CX/shiny/64.png",
    "Cocos (Keeling) Islands": "https://www.countryflags.io/CC/shiny/64.png",
    "Colombia": "https://www.countryflags.io/CO/shiny/64.png",
    "Comoros": "https://www.countryflags.io/KM/shiny/64.png",
    "Congo": "https://www.countryflags.io/CG/shiny/64.png",
    "Congo, The Democratic Republic of the": "https://www.countryflags.io/CD/shiny/64.png",
    "Cook Islands": "https://www.countryflags.io/CK/shiny/64.png",
    "Costa Rica": "https://www.countryflags.io/CR/shiny/64.png",
    "Cote D'Ivoire": "https://www.countryflags.io/CI/shiny/64.png",
    "Croatia": "https://www.countryflags.io/HR/shiny/64.png",
    "Cuba": "https://www.countryflags.io/CU/shiny/64.png",
    "Cyprus": "https://www.countryflags.io/CY/shiny/64.png",
    "Czech Republic": "https://www.countryflags.io/CZ/shiny/64.png",
    "Denmark": "https://www.countryflags.io/DK/shiny/64.png",
    "Djibouti": "https://www.countryflags.io/DJ/shiny/64.png",
    "Dominica": "https://www.countryflags.io/DM/shiny/64.png",
    "Dominican Republic": "https://www.countryflags.io/DO/shiny/64.png",
    "Ecuador": "https://www.countryflags.io/EC/shiny/64.png",
    "Egypt": "https://www.countryflags.io/EG/shiny/64.png",
    "El Salvador": "https://www.countryflags.io/SV/shiny/64.png",
    "Equatorial Guinea": "https://www.countryflags.io/GQ/shiny/64.png",
    "Eritrea": "https://www.countryflags.io/ER/shiny/64.png",
    "Estonia": "https://www.countryflags.io/EE/shiny/64.png",
    "Ethiopia": "https://www.countryflags.io/ET/shiny/64.png",
    "Falkland Islands (Malvinas)": "https://www.countryflags.io/FK/shiny/64.png",
    "Faroe Islands": "https://www.countryflags.io/FO/shiny/64.png",
    "Fiji": "https://www.countryflags.io/FJ/shiny/64.png",
    "Finland": "https://www.countryflags.io/FI/shiny/64.png",
    "France": "https://www.countryflags.io/FR/shiny/64.png",
    "French Guiana": "https://www.countryflags.io/GF/shiny/64.png",
    "French Polynesia": "https://www.countryflags.io/PF/shiny/64.png",
    "French Southern Territories": "https://www.countryflags.io/TF/shiny/64.png",
    "Gabon": "https://www.countryflags.io/GA/shiny/64.png",
    "Gambia": "https://www.countryflags.io/GM/shiny/64.png",
    "Georgia": "https://www.countryflags.io/GE/shiny/64.png",
    "Germany": "https://www.countryflags.io/DE/shiny/64.png",
    "Ghana": "https://www.countryflags.io/GH/shiny/64.png",
    "Gibraltar": "https://www.countryflags.io/GI/shiny/64.png",
    "Greece": "https://www.countryflags.io/GR/shiny/64.png",
    "Greenland": "https://www.countryflags.io/GL/shiny/64.png",
    "Grenada": "https://www.countryflags.io/GD/shiny/64.png",
    "Guadeloupe": "https://www.countryflags.io/GP/shiny/64.png",
    "Guam": "https://www.countryflags.io/GU/shiny/64.png",
    "Guatemala": "https://www.countryflags.io/GT/shiny/64.png",
    "Guernsey": "https://www.countryflags.io/GG/shiny/64.png",
    "Guinea": "https://www.countryflags.io/GN/shiny/64.png",
    "Guinea-Bissau": "https://www.countryflags.io/GW/shiny/64.png",
    "Guyana": "https://www.countryflags.io/GY/shiny/64.png",
    "Haiti": "https://www.countryflags.io/HT/shiny/64.png",
    "Heard Island and Mcdonald Islands": "https://www.countryflags.io/HM/shiny/64.png",
    "Holy See (Vatican City State)": "https://www.countryflags.io/VA/shiny/64.png",
    "Honduras": "https://www.countryflags.io/HN/shiny/64.png",
    "Hong Kong": "https://www.countryflags.io/HK/shiny/64.png",
    "Hungary": "https://www.countryflags.io/HU/shiny/64.png",
    "Iceland": "https://www.countryflags.io/IS/shiny/64.png",
    "India": "https://www.countryflags.io/IN/shiny/64.png",
    "Indonesia": "https://www.countryflags.io/ID/shiny/64.png",
    "Iran, Islamic Republic Of": "https://www.countryflags.io/IR/shiny/64.png",
    "Iraq": "https://www.countryflags.io/IQ/shiny/64.png",
    "Ireland": "https://www.countryflags.io/IE/shiny/64.png",
    "Isle of Man": "https://www.countryflags.io/IM/shiny/64.png",
    "Israel": "https://www.countryflags.io/IL/shiny/64.png",
    "Italy": "https://www.countryflags.io/IT/shiny/64.png",
    "Jamaica": "https://www.countryflags.io/JM/shiny/64.png",
    "Japan": "https://www.countryflags.io/JP/shiny/64.png",
    "Jersey": "https://www.countryflags.io/JE/shiny/64.png",
    "Jordan": "https://www.countryflags.io/JO/shiny/64.png",
    "Kazakhstan": "https://www.countryflags.io/KZ/shiny/64.png",
    "Kenya": "https://www.countryflags.io/KE/shiny/64.png",
    "Kiribati": "https://www.countryflags.io/KI/shiny/64.png",
    "Korea, Democratic People'S Republic of": "https://www.countryflags.io/KP/shiny/64.png",
    "Korea, Republic of": "https://www.countryflags.io/KR/shiny/64.png",
    "Kuwait": "https://www.countryflags.io/KW/shiny/64.png",
    "Kyrgyzstan": "https://www.countryflags.io/KG/shiny/64.png",
    "Lao People'S Democratic Republic": "https://www.countryflags.io/LA/shiny/64.png",
    "Latvia": "https://www.countryflags.io/LV/shiny/64.png",
    "Lebanon": "https://www.countryflags.io/LB/shiny/64.png",
    "Lesotho": "https://www.countryflags.io/LS/shiny/64.png",
    "Liberia": "https://www.countryflags.io/LR/shiny/64.png",
    "Libyan Arab Jamahiriya": "https://www.countryflags.io/LY/shiny/64.png",
    "Liechtenstein": "https://www.countryflags.io/LI/shiny/64.png",
    "Lithuania": "https://www.countryflags.io/LT/shiny/64.png",
    "Luxembourg": "https://www.countryflags.io/LU/shiny/64.png",
    "Macao": "https://www.countryflags.io/MO/shiny/64.png",
    "Macedonia, The Former Yugoslav Republic of": "https://www.countryflags.io/MK/shiny/64.png",
    "Madagascar": "https://www.countryflags.io/MG/shiny/64.png",
    "Malawi": "https://www.countryflags.io/MW/shiny/64.png",
    "Malaysia": "https://www.countryflags.io/MY/shiny/64.png",
    "Maldives": "https://www.countryflags.io/MV/shiny/64.png",
    "Mali": "https://www.countryflags.io/ML/shiny/64.png",
    "Malta": "https://www.countryflags.io/MT/shiny/64.png",
    "Marshall Islands": "https://www.countryflags.io/MH/shiny/64.png",
    "Martinique": "https://www.countryflags.io/MQ/shiny/64.png",
    "Mauritania": "https://www.countryflags.io/MR/shiny/64.png",
    "Mauritius": "https://www.countryflags.io/MU/shiny/64.png",
    "Mayotte": "https://www.countryflags.io/YT/shiny/64.png",
    "Mexico": "https://www.countryflags.io/MX/shiny/64.png",
    "Micronesia, Federated States of": "https://www.countryflags.io/FM/shiny/64.png",
    "Moldova, Republic of": "https://www.countryflags.io/MD/shiny/64.png",
    "Monaco": "https://www.countryflags.io/MC/shiny/64.png",
    "Mongolia": "https://www.countryflags.io/MN/shiny/64.png",
    "Montserrat": "https://www.countryflags.io/MS/shiny/64.png",
    "Morocco": "https://www.countryflags.io/MA/shiny/64.png",
    "Mozambique": "https://www.countryflags.io/MZ/shiny/64.png",
    "Myanmar": "https://www.countryflags.io/MM/shiny/64.png",
    "Namibia": "https://www.countryflags.io/NA/shiny/64.png",
    "Nauru": "https://www.countryflags.io/NR/shiny/64.png",
    "Nepal": "https://www.countryflags.io/NP/shiny/64.png",
    "Netherlands": "https://www.countryflags.io/NL/shiny/64.png",
    "Netherlands Antilles": "https://www.countryflags.io/AN/shiny/64.png",
    "New Caledonia": "https://www.countryflags.io/NC/shiny/64.png",
    "New Zealand": "https://www.countryflags.io/NZ/shiny/64.png",
    "Nicaragua": "https://www.countryflags.io/NI/shiny/64.png",
    "Niger": "https://www.countryflags.io/NE/shiny/64.png",
    "Nigeria": "https://www.countryflags.io/NG/shiny/64.png",
    "Niue": "https://www.countryflags.io/NU/shiny/64.png",
    "Norfolk Island": "https://www.countryflags.io/NF/shiny/64.png",
    "Northern Mariana Islands": "https://www.countryflags.io/MP/shiny/64.png",
    "Norway": "https://www.countryflags.io/NO/shiny/64.png",
    "Oman": "https://www.countryflags.io/OM/shiny/64.png",
    "Pakistan": "https://www.countryflags.io/PK/shiny/64.png",
    "Palau": "https://www.countryflags.io/PW/shiny/64.png",
    "Palestinian Territory, Occupied": "https://www.countryflags.io/PS/shiny/64.png",
    "Panama": "https://www.countryflags.io/PA/shiny/64.png",
    "Papua New Guinea": "https://www.countryflags.io/PG/shiny/64.png",
    "Paraguay": "https://www.countryflags.io/PY/shiny/64.png",
    "Peru": "https://www.countryflags.io/PE/shiny/64.png",
    "Philippines": "https://www.countryflags.io/PH/shiny/64.png",
    "Pitcairn": "https://www.countryflags.io/PN/shiny/64.png",
    "Poland": "https://www.countryflags.io/PL/shiny/64.png",
    "Portugal": "https://www.countryflags.io/PT/shiny/64.png",
    "Puerto Rico": "https://www.countryflags.io/PR/shiny/64.png",
    "Qatar": "https://www.countryflags.io/QA/shiny/64.png",
    "Reunion": "https://www.countryflags.io/RE/shiny/64.png",
    "Romania": "https://www.countryflags.io/RO/shiny/64.png",
    "Russian Federation": "https://www.countryflags.io/RU/shiny/64.png",
    "RWANDA": "https://www.countryflags.io/RW/shiny/64.png",
    "Saint Helena": "https://www.countryflags.io/SH/shiny/64.png",
    "Saint Kitts and Nevis": "https://www.countryflags.io/KN/shiny/64.png",
    "Saint Lucia": "https://www.countryflags.io/LC/shiny/64.png",
    "Saint Pierre and Miquelon": "https://www.countryflags.io/PM/shiny/64.png",
    "Saint Vincent and the Grenadines": "https://www.countryflags.io/VC/shiny/64.png",
    "Samoa": "https://www.countryflags.io/WS/shiny/64.png",
    "San Marino": "https://www.countryflags.io/SM/shiny/64.png",
    "Sao Tome and Principe": "https://www.countryflags.io/ST/shiny/64.png",
    "Saudi Arabia": "https://www.countryflags.io/SA/shiny/64.png",
    "Senegal": "https://www.countryflags.io/SN/shiny/64.png",
    "Serbia and Montenegro": "https://www.countryflags.io/CS/shiny/64.png",
    "Seychelles": "https://www.countryflags.io/SC/shiny/64.png",
    "Sierra Leone": "https://www.countryflags.io/SL/shiny/64.png",
    "Singapore": "https://www.countryflags.io/SG/shiny/64.png",
    "Slovakia": "https://www.countryflags.io/SK/shiny/64.png",
    "Slovenia": "https://www.countryflags.io/SI/shiny/64.png",
    "Solomon Islands": "https://www.countryflags.io/SB/shiny/64.png",
    "Somalia": "https://www.countryflags.io/SO/shiny/64.png",
    "South Africa": "https://www.countryflags.io/ZA/shiny/64.png",
    "South Georgia and the South Sandwich Islands": "https://www.countryflags.io/GS/shiny/64.png",
    "Spain": "https://www.countryflags.io/ES/shiny/64.png",
    "Sri Lanka": "https://www.countryflags.io/LK/shiny/64.png",
    "Sudan": "https://www.countryflags.io/SD/shiny/64.png",
    "Suri'name'": "https://www.countryflags.io/SR/shiny/64.png",
    "Svalbard and Jan Mayen": "https://www.countryflags.io/SJ/shiny/64.png",
    "Swaziland": "https://www.countryflags.io/SZ/shiny/64.png",
    "Sweden": "https://www.countryflags.io/SE/shiny/64.png",
    "Switzerland": "https://www.countryflags.io/CH/shiny/64.png",
    "Syrian Arab Republic": "https://www.countryflags.io/SY/shiny/64.png",
    "Taiwan, Province of China": "https://www.countryflags.io/TW/shiny/64.png",
    "Tajikistan": "https://www.countryflags.io/TJ/shiny/64.png",
    "Tanzania, United Republic of": "https://www.countryflags.io/TZ/shiny/64.png",
    "Thailand": "https://www.countryflags.io/TH/shiny/64.png",
    "Timor-Leste": "https://www.countryflags.io/TL/shiny/64.png",
    "Togo": "https://www.countryflags.io/TG/shiny/64.png",
    "Tokelau": "https://www.countryflags.io/TK/shiny/64.png",
    "Tonga": "https://www.countryflags.io/TO/shiny/64.png",
    "Trinidad and Tobago": "https://www.countryflags.io/TT/shiny/64.png",
    "Tunisia": "https://www.countryflags.io/TN/shiny/64.png",
    "Turkey": "https://www.countryflags.io/TR/shiny/64.png",
    "Turkmenistan": "https://www.countryflags.io/TM/shiny/64.png",
    "Turks and Caicos Islands": "https://www.countryflags.io/TC/shiny/64.png",
    "Tuvalu": "https://www.countryflags.io/TV/shiny/64.png",
    "Uganda": "https://www.countryflags.io/UG/shiny/64.png",
    "Ukraine": "https://www.countryflags.io/UA/shiny/64.png",
    "United Arab Emirates": "https://www.countryflags.io/AE/shiny/64.png",
    "United Kingdom": "https://www.countryflags.io/GB/shiny/64.png",
    "United States": "https://www.countryflags.io/US/shiny/64.png",
    "United States Minor Outlying Islands": "https://www.countryflags.io/UM/shiny/64.png",
    "Uruguay": "https://www.countryflags.io/UY/shiny/64.png",
    "Uzbekistan": "https://www.countryflags.io/UZ/shiny/64.png",
    "Vanuatu": "https://www.countryflags.io/VU/shiny/64.png",
    "Venezuela": "https://www.countryflags.io/VE/shiny/64.png",
    "Viet Nam": "https://www.countryflags.io/VN/shiny/64.png",
    "Virgin Islands, British": "https://www.countryflags.io/VG/shiny/64.png",
    "Virgin Islands, U.S.": "https://www.countryflags.io/VI/shiny/64.png",
    "Wallis and Futuna": "https://www.countryflags.io/WF/shiny/64.png",
    "Western Sahara": "https://www.countryflags.io/EH/shiny/64.png",
    "Yemen": "https://www.countryflags.io/YE/shiny/64.png",
    "Zambia": "https://www.countryflags.io/ZM/shiny/64.png",
    "Zimbabwe": "https://www.countryflags.io/ZW/shiny/64.png",
}